name: Build and Deploy

on:
  workflow_call:

jobs :
  build:
    uses: ./.github/workflows/reusable/build.yml

  deploy-preprod:
    needs: build
    uses: ./.github/workflows/reusable/deploy.yml
    with:
      environment: preprod

  deploy-prod:
    needs: deploy-preprod
    uses: ./.github/workflows/reusable/deploy.yml
    with:
      environment: prod

  deploy-nimdta:
    needs: deploy-preprod
    uses: ./.github/workflows/reusable/deploy.yml
    with:
      environment: nimdta
