name: Deploy to ECS

on:
  workflow_call:
    inputs:
      environment:
        description: The target environment for the deployment.
        required: true
        type: string

jobs:
  deploy:
    name: Deploy ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ${{ inputs.environment }}
        run: echo deploy to ${{ inputs.environment }} step executed.
