name: Build and Deploy

on:
  workflow_call:

jobs :
  build:
    uses: ./.github/workflows/build-gradle.yml

  deploy-preprod-a:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preprod

  deploy-prod-a:
    needs: deploy-preprod-a
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod

  deploy-preprod-b:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preprod
      name: test_override_name

  deploy-prod-b:
    needs: deploy-preprod-b
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      name: test_override_name