name: Build and Deploy

on:
  workflow_call:

jobs :
  build:
    uses: ./.github/workflows/build.yml

  deploy-preprod:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preprod

  deploy-prod:
    needs: deploy-preprod
    uses: ./.github/workflows/deploy.yml
    strategy:
      matrix:
        environment: [prod, nimdta]
    with:
      environment: ${{ matrix.environment }}
