name: Build and Deploy

on:
  workflow_call:
    inputs:
      build-tool:
        description: the build tool to use
        required: false
        default: gradle
        type: string

jobs :
  build:
    uses: ./.github/workflows/build-${{ inputs.build-tool }}.yml

  deploy-preprod:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preprod

  deploy-prod:
    needs: deploy-preprod
    uses: ./.github/workflows/deploy.yml
    strategy:
      matrix:
        environment: [prod, nimdta]
    with:
      environment: ${{ matrix.environment }}
