name: Build and Deploy

on:
  push:
    branches:
      - main

jobs :
  call-build-workflow:
    uses: ./.github/workflows/build.yml

  call-deploy-workflow:
    needs: call-build-workflow
    uses: ./.github/workflows/deploy.yml
