name: Deploy - ${{ input.environment }}

on:
  workflow_call:
    input:
      environment:
        description: The target environment for the deployment.
        required: true
        type: string

jobs:
  deploy-job:
    name: Deploy Job - ${{ input.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step - ${{ input.environment }}
        run: echo deploy to ${{ input.environment }} step executed.
