name: Deploy - ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: The target environment for the deployment.
        required: true
        type: string

jobs:
  deploy-job:
    name: Deploy Job - ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step - ${{ inputs.environment }}
        run: echo deploy to ${{ inputs.environment }} step executed.
