name: Deploy to ECS

on:
  workflow_call:
    inputs:
      environment:
        description: The target environment for the deployment.
        required: true
        type: string
      service_name:
        description: The target environment for the deployment.
        required: false
        default: ${{ github.event.repository.name }}
        type: string

jobs:
  deploy:
    name: Deploy ${{ inputs.environment }} ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Deploy ${{ inputs.environment }} ${{ inputs.service_name }}
        run: echo deploy to ${{ inputs.environment }}, with name ${{ inputs.service_name }}.
